config/routes.rb
TCinGC::Application.routes.draw do
  resources :student_scorecards

  resources :project_scorecards

  resources :project_applications

  resources :student_applications

  resources :partners
  
  resources :assignments

  devise_for :users

  root :to => 'home#index'

  
  root :to => "home#index"
end

app/models/project_scorecard.rb
class ProjectScorecard < ActiveRecord::Base
	# Setup accessible (or protected) attributes for your model
	attr_accessible :user_id, :project_application_id, :database_score, :web_app_score, :design_score, :tech_plan_score, :web_dev_score, :content_mgt_score, :tech_support_score, :geo_infosys_score, :egov_score, :ehealth_score, :security_score, :updated_by 
	
	# Relationships
	belongs_to :user
	belongs_to :project_application
end

app/controllers/project_scorecards_controller.rb
class ProjectScorecardsController < ApplicationController
  # GET /project_scorecards
  # GET /project_scorecards.json
  def index
    @project_scorecards = ProjectScorecard.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @project_scorecards }
    end
  end

  # GET /project_scorecards/1
  # GET /project_scorecards/1.json
  def show
    @project_scorecard = ProjectScorecard.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project_scorecard }
    end
  end

  # GET /project_scorecards/new
  # GET /project_scorecards/new.json
  def new
    @project_scorecard = ProjectScorecard.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project_scorecard }
    end
  end

  # GET /project_scorecards/1/edit
  def edit
    @project_scorecard = ProjectScorecard.find(params[:id])
  end

  # POST /project_scorecards
  # POST /project_scorecards.json
  def create
    @project_scorecard = ProjectScorecard.new(params[:project_scorecard])

    respond_to do |format|
      if @project_scorecard.save
        format.html { redirect_to @project_scorecard, notice: 'Project scorecard was successfully created.' }
        format.json { render json: @project_scorecard, status: :created, location: @project_scorecard }
      else
        format.html { render action: "new" }
        format.json { render json: @project_scorecard.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /project_scorecards/1
  # PUT /project_scorecards/1.json
  def update
    @project_scorecard = ProjectScorecard.find(params[:id])

    respond_to do |format|
      if @project_scorecard.update_attributes(params[:project_scorecard])
        format.html { redirect_to @project_scorecard, notice: 'Project scorecard was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @project_scorecard.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /project_scorecards/1
  # DELETE /project_scorecards/1.json
  def destroy
    @project_scorecard = ProjectScorecard.find(params[:id])
    @project_scorecard.destroy

    respond_to do |format|
      format.html { redirect_to project_scorecards_url }
      format.json { head :ok }
    end
  end
end

app/helpers/project_scorecards_helper.rb
module ProjectScorecardsHelper
end

app/views/project_scorecards/_form.html.erb
<%= form_for(@project_scorecard) do |f| %>
  <% if @project_scorecard.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project_scorecard.errors.count, "error") %> prohibited this project_scorecard from being saved:</h2>

      <ul>
      <% @project_scorecard.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :project_application_id %><br />
    <%= f.number_field :project_application_id %>
  </div>
  <div class="field">
    <%= f.label :database_score %><br />
    <%= f.number_field :database_score %>
  </div>
  <div class="field">
    <%= f.label :web_app_score %><br />
    <%= f.number_field :web_app_score %>
  </div>
  <div class="field">
    <%= f.label :design_score %><br />
    <%= f.number_field :design_score %>
  </div>
  <div class="field">
    <%= f.label :tech_plan_score %><br />
    <%= f.number_field :tech_plan_score %>
  </div>
  <div class="field">
    <%= f.label :web_dev_score %><br />
    <%= f.number_field :web_dev_score %>
  </div>
  <div class="field">
    <%= f.label :content_mgt_score %><br />
    <%= f.number_field :content_mgt_score %>
  </div>
  <div class="field">
    <%= f.label :tech_support_score %><br />
    <%= f.number_field :tech_support_score %>
  </div>
  <div class="field">
    <%= f.label :geo_infosys_score %><br />
    <%= f.number_field :geo_infosys_score %>
  </div>
  <div class="field">
    <%= f.label :egov_score %><br />
    <%= f.number_field :egov_score %>
  </div>
  <div class="field">
    <%= f.label :ehealth_score %><br />
    <%= f.number_field :ehealth_score %>
  </div>
  <div class="field">
    <%= f.label :security_score %><br />
    <%= f.number_field :security_score %>
  </div>
  <div class="field">
    <%= f.label :updated_by %><br />
    <%= f.number_field :updated_by %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/project_scorecards/edit.html.erb
<h1>Editing project_scorecard</h1>

<%= render 'form' %>

<%= link_to 'Show', @project_scorecard %> |
<%= link_to 'Back', project_scorecards_path %>

app/views/project_scorecards/index.html.erb
<h1>Listing project_scorecards</h1>

<table>
  <tr>
    <th>User</th>
    <th>Project application</th>
    <th>Database score</th>
    <th>Web app score</th>
    <th>Design score</th>
    <th>Tech plan score</th>
    <th>Web dev score</th>
    <th>Content mgt score</th>
    <th>Tech support score</th>
    <th>Geo infosys score</th>
    <th>Egov score</th>
    <th>Ehealth score</th>
    <th>Security score</th>
    <th>Updated by</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @project_scorecards.each do |project_scorecard| %>
  <tr>
    <td><%= project_scorecard.user_id %></td>
    <td><%= project_scorecard.project_application_id %></td>
    <td><%= project_scorecard.database_score %></td>
    <td><%= project_scorecard.web_app_score %></td>
    <td><%= project_scorecard.design_score %></td>
    <td><%= project_scorecard.tech_plan_score %></td>
    <td><%= project_scorecard.web_dev_score %></td>
    <td><%= project_scorecard.content_mgt_score %></td>
    <td><%= project_scorecard.tech_support_score %></td>
    <td><%= project_scorecard.geo_infosys_score %></td>
    <td><%= project_scorecard.egov_score %></td>
    <td><%= project_scorecard.ehealth_score %></td>
    <td><%= project_scorecard.security_score %></td>
    <td><%= project_scorecard.updated_by %></td>
    <td><%= link_to 'Show', project_scorecard %></td>
    <td><%= link_to 'Edit', edit_project_scorecard_path(project_scorecard) %></td>
    <td><%= link_to 'Destroy', project_scorecard, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Project scorecard', new_project_scorecard_path %>

app/views/project_scorecards/new.html.erb
<h1>New project_scorecard</h1>

<%= render 'form' %>

<%= link_to 'Back', project_scorecards_path %>

app/views/project_scorecards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @project_scorecard.user_id %>
</p>

<p>
  <b>Project application:</b>
  <%= @project_scorecard.project_application_id %>
</p>

<p>
  <b>Database score:</b>
  <%= @project_scorecard.database_score %>
</p>

<p>
  <b>Web app score:</b>
  <%= @project_scorecard.web_app_score %>
</p>

<p>
  <b>Design score:</b>
  <%= @project_scorecard.design_score %>
</p>

<p>
  <b>Tech plan score:</b>
  <%= @project_scorecard.tech_plan_score %>
</p>

<p>
  <b>Web dev score:</b>
  <%= @project_scorecard.web_dev_score %>
</p>

<p>
  <b>Content mgt score:</b>
  <%= @project_scorecard.content_mgt_score %>
</p>

<p>
  <b>Tech support score:</b>
  <%= @project_scorecard.tech_support_score %>
</p>

<p>
  <b>Geo infosys score:</b>
  <%= @project_scorecard.geo_infosys_score %>
</p>

<p>
  <b>Egov score:</b>
  <%= @project_scorecard.egov_score %>
</p>

<p>
  <b>Ehealth score:</b>
  <%= @project_scorecard.ehealth_score %>
</p>

<p>
  <b>Security score:</b>
  <%= @project_scorecard.security_score %>
</p>

<p>
  <b>Updated by:</b>
  <%= @project_scorecard.updated_by %>
</p>


<%= link_to 'Edit', edit_project_scorecard_path(@project_scorecard) %> |
<%= link_to 'Back', project_scorecards_path %>