config/routes.rb
TCinGC::Application.routes.draw do
  resources :student_scorecards

  resources :project_scorecards

  resources :project_applications

  resources :student_applications

  resources :partners
  
  resources :assignments

  devise_for :users

  root :to => 'home#index'

  
  root :to => "home#index"
end

app/models/student_scorecard.rb
class StudentScorecard < ActiveRecord::Base
	# Setup accessible (or protected) attributes for your model
	attr_accessible :user_id, :student_application_id, :resume_score, transcript_score, :statement_of_interest_score, :special_class_score, :database_score, :web_app_score, :design_score, :tech_plan_score, :web_dev_score, :content_mgt_score, :tech_support_score, :geo_infosys_score, :egov_score, :ehealth_score, :security_score, :updated_by 
	
	# Relationships
	belongs_to :user
	belongs_to :student_application
end

app/controllers/student_scorecards_controller.rb
class StudentScorecardsController < ApplicationController
  # GET /student_scorecards
  # GET /student_scorecards.json
  def index
    @student_scorecards = StudentScorecard.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @student_scorecards }
    end
  end

  # GET /student_scorecards/1
  # GET /student_scorecards/1.json
  def show
    @student_scorecard = StudentScorecard.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @student_scorecard }
    end
  end

  # GET /student_scorecards/new
  # GET /student_scorecards/new.json
  def new
    @student_scorecard = StudentScorecard.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @student_scorecard }
    end
  end

  # GET /student_scorecards/1/edit
  def edit
    @student_scorecard = StudentScorecard.find(params[:id])
  end

  # POST /student_scorecards
  # POST /student_scorecards.json
  def create
    @student_scorecard = StudentScorecard.new(params[:student_scorecard])

    respond_to do |format|
      if @student_scorecard.save
        format.html { redirect_to @student_scorecard, notice: 'Student scorecard was successfully created.' }
        format.json { render json: @student_scorecard, status: :created, location: @student_scorecard }
      else
        format.html { render action: "new" }
        format.json { render json: @student_scorecard.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /student_scorecards/1
  # PUT /student_scorecards/1.json
  def update
    @student_scorecard = StudentScorecard.find(params[:id])

    respond_to do |format|
      if @student_scorecard.update_attributes(params[:student_scorecard])
        format.html { redirect_to @student_scorecard, notice: 'Student scorecard was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @student_scorecard.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /student_scorecards/1
  # DELETE /student_scorecards/1.json
  def destroy
    @student_scorecard = StudentScorecard.find(params[:id])
    @student_scorecard.destroy

    respond_to do |format|
      format.html { redirect_to student_scorecards_url }
      format.json { head :ok }
    end
  end
end

app/helpers/student_scorecards_helper.rb
module StudentScorecardsHelper
end

app/views/student_scorecards/_form.html.erb
<%= form_for(@student_scorecard) do |f| %>
  <% if @student_scorecard.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student_scorecard.errors.count, "error") %> prohibited this student_scorecard from being saved:</h2>

      <ul>
      <% @student_scorecard.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :student_application_id %><br />
    <%= f.number_field :student_application_id %>
  </div>
  <div class="field">
    <%= f.label :resume_score %><br />
    <%= f.number_field :resume_score %>
  </div>
  <div class="field">
    <%= f.label :transcript_score %><br />
    <%= f.number_field :transcript_score %>
  </div>
  <div class="field">
    <%= f.label :statement_of_interest_score %><br />
    <%= f.number_field :statement_of_interest_score %>
  </div>
  <div class="field">
    <%= f.label :special_class_score %><br />
    <%= f.number_field :special_class_score %>
  </div>
  <div class="field">
    <%= f.label :database_score %><br />
    <%= f.number_field :database_score %>
  </div>
  <div class="field">
    <%= f.label :web_app_score %><br />
    <%= f.number_field :web_app_score %>
  </div>
  <div class="field">
    <%= f.label :design_score %><br />
    <%= f.number_field :design_score %>
  </div>
  <div class="field">
    <%= f.label :tech_plan_score %><br />
    <%= f.number_field :tech_plan_score %>
  </div>
  <div class="field">
    <%= f.label :web_dev_score %><br />
    <%= f.number_field :web_dev_score %>
  </div>
  <div class="field">
    <%= f.label :content_mgt_score %><br />
    <%= f.number_field :content_mgt_score %>
  </div>
  <div class="field">
    <%= f.label :tech_support_score %><br />
    <%= f.number_field :tech_support_score %>
  </div>
  <div class="field">
    <%= f.label :geo_infosys_score %><br />
    <%= f.number_field :geo_infosys_score %>
  </div>
  <div class="field">
    <%= f.label :egov_score %><br />
    <%= f.number_field :egov_score %>
  </div>
  <div class="field">
    <%= f.label :ehealth_score %><br />
    <%= f.number_field :ehealth_score %>
  </div>
  <div class="field">
    <%= f.label :security_score %><br />
    <%= f.number_field :security_score %>
  </div>
  <div class="field">
    <%= f.label :updated_by %><br />
    <%= f.number_field :updated_by %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/student_scorecards/edit.html.erb
<h1>Editing student_scorecard</h1>

<%= render 'form' %>

<%= link_to 'Show', @student_scorecard %> |
<%= link_to 'Back', student_scorecards_path %>

app/views/student_scorecards/index.html.erb
<h1>Listing student_scorecards</h1>

<table>
  <tr>
    <th>User</th>
    <th>Student application</th>
    <th>Resume score</th>
    <th>Transcript score</th>
    <th>Statement of interest score</th>
    <th>Special class score</th>
    <th>Database score</th>
    <th>Web app score</th>
    <th>Design score</th>
    <th>Tech plan score</th>
    <th>Web dev score</th>
    <th>Content mgt score</th>
    <th>Tech support score</th>
    <th>Geo infosys score</th>
    <th>Egov score</th>
    <th>Ehealth score</th>
    <th>Security score</th>
    <th>Updated by</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @student_scorecards.each do |student_scorecard| %>
  <tr>
    <td><%= student_scorecard.user_id %></td>
    <td><%= student_scorecard.student_application_id %></td>
    <td><%= student_scorecard.resume_score %></td>
    <td><%= student_scorecard.transcript_score %></td>
    <td><%= student_scorecard.statement_of_interest_score %></td>
    <td><%= student_scorecard.special_class_score %></td>
    <td><%= student_scorecard.database_score %></td>
    <td><%= student_scorecard.web_app_score %></td>
    <td><%= student_scorecard.design_score %></td>
    <td><%= student_scorecard.tech_plan_score %></td>
    <td><%= student_scorecard.web_dev_score %></td>
    <td><%= student_scorecard.content_mgt_score %></td>
    <td><%= student_scorecard.tech_support_score %></td>
    <td><%= student_scorecard.geo_infosys_score %></td>
    <td><%= student_scorecard.egov_score %></td>
    <td><%= student_scorecard.ehealth_score %></td>
    <td><%= student_scorecard.security_score %></td>
    <td><%= student_scorecard.updated_by %></td>
    <td><%= link_to 'Show', student_scorecard %></td>
    <td><%= link_to 'Edit', edit_student_scorecard_path(student_scorecard) %></td>
    <td><%= link_to 'Destroy', student_scorecard, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Student scorecard', new_student_scorecard_path %>

app/views/student_scorecards/new.html.erb
<h1>New student_scorecard</h1>

<%= render 'form' %>

<%= link_to 'Back', student_scorecards_path %>

app/views/student_scorecards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @student_scorecard.user_id %>
</p>

<p>
  <b>Student application:</b>
  <%= @student_scorecard.student_application_id %>
</p>

<p>
  <b>Resume score:</b>
  <%= @student_scorecard.resume_score %>
</p>

<p>
  <b>Transcript score:</b>
  <%= @student_scorecard.transcript_score %>
</p>

<p>
  <b>Statement of interest score:</b>
  <%= @student_scorecard.statement_of_interest_score %>
</p>

<p>
  <b>Special class score:</b>
  <%= @student_scorecard.special_class_score %>
</p>

<p>
  <b>Database score:</b>
  <%= @student_scorecard.database_score %>
</p>

<p>
  <b>Web app score:</b>
  <%= @student_scorecard.web_app_score %>
</p>

<p>
  <b>Design score:</b>
  <%= @student_scorecard.design_score %>
</p>

<p>
  <b>Tech plan score:</b>
  <%= @student_scorecard.tech_plan_score %>
</p>

<p>
  <b>Web dev score:</b>
  <%= @student_scorecard.web_dev_score %>
</p>

<p>
  <b>Content mgt score:</b>
  <%= @student_scorecard.content_mgt_score %>
</p>

<p>
  <b>Tech support score:</b>
  <%= @student_scorecard.tech_support_score %>
</p>

<p>
  <b>Geo infosys score:</b>
  <%= @student_scorecard.geo_infosys_score %>
</p>

<p>
  <b>Egov score:</b>
  <%= @student_scorecard.egov_score %>
</p>

<p>
  <b>Ehealth score:</b>
  <%= @student_scorecard.ehealth_score %>
</p>

<p>
  <b>Security score:</b>
  <%= @student_scorecard.security_score %>
</p>

<p>
  <b>Updated by:</b>
  <%= @student_scorecard.updated_by %>
</p>


<%= link_to 'Edit', edit_student_scorecard_path(@student_scorecard) %> |
<%= link_to 'Back', student_scorecards_path %>