config/routes.rb
TCinGC::Application.routes.draw do
  resources :student_scorecards

  resources :project_scorecards

  resources :project_applications

  resources :student_applications

  resources :partners
  
  resources :assignments

  devise_for :users

  root :to => 'home#index'

  
  root :to => "home#index"
end

app/models/project_application.rb
class ProjectApplication < ActiveRecord::Base
	# Setup accessible (or protected) attributes for your model
	attr_accesible :partner_id, :description, :number_of_consultants, :accepted, :open

	# Relationships
	belongs_to :partner
	has_many :project_scorecards
end

app/controllers/project_applications_controller.rb
class ProjectApplicationsController < ApplicationController
  # GET /project_applications
  # GET /project_applications.json
  def index
    @project_applications = ProjectApplication.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @project_applications }
    end
  end

  # GET /project_applications/1
  # GET /project_applications/1.json
  def show
    @project_application = ProjectApplication.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project_application }
    end
  end

  # GET /project_applications/new
  # GET /project_applications/new.json
  def new
    @project_application = ProjectApplication.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project_application }
    end
  end

  # GET /project_applications/1/edit
  def edit
    @project_application = ProjectApplication.find(params[:id])
  end

  # POST /project_applications
  # POST /project_applications.json
  def create
    @project_application = ProjectApplication.new(params[:project_application])

    respond_to do |format|
      if @project_application.save
        format.html { redirect_to @project_application, notice: 'Project application was successfully created.' }
        format.json { render json: @project_application, status: :created, location: @project_application }
      else
        format.html { render action: "new" }
        format.json { render json: @project_application.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /project_applications/1
  # PUT /project_applications/1.json
  def update
    @project_application = ProjectApplication.find(params[:id])

    respond_to do |format|
      if @project_application.update_attributes(params[:project_application])
        format.html { redirect_to @project_application, notice: 'Project application was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @project_application.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /project_applications/1
  # DELETE /project_applications/1.json
  def destroy
    @project_application = ProjectApplication.find(params[:id])
    @project_application.destroy

    respond_to do |format|
      format.html { redirect_to project_applications_url }
      format.json { head :ok }
    end
  end
end

app/helpers/project_applications_helper.rb
module ProjectApplicationsHelper
end

app/views/project_applications/_form.html.erb
<%= form_for(@project_application) do |f| %>
  <% if @project_application.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project_application.errors.count, "error") %> prohibited this project_application from being saved:</h2>

      <ul>
      <% @project_application.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :partner_id %><br />
    <%= f.number_field :partner_id %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :number_of_consultants %><br />
    <%= f.number_field :number_of_consultants %>
  </div>
  <div class="field">
    <%= f.label :accepted %><br />
    <%= f.check_box :accepted %>
  </div>
  <div class="field">
    <%= f.label :open %><br />
    <%= f.check_box :open %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/project_applications/edit.html.erb
<h1>Editing project_application</h1>

<%= render 'form' %>

<%= link_to 'Show', @project_application %> |
<%= link_to 'Back', project_applications_path %>

app/views/project_applications/index.html.erb
<h1>Listing project_applications</h1>

<table>
  <tr>
    <th>Partner</th>
    <th>Description</th>
    <th>Number of consultants</th>
    <th>Accepted</th>
    <th>Open</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @project_applications.each do |project_application| %>
  <tr>
    <td><%= project_application.partner_id %></td>
    <td><%= project_application.description %></td>
    <td><%= project_application.number_of_consultants %></td>
    <td><%= project_application.accepted %></td>
    <td><%= project_application.open %></td>
    <td><%= link_to 'Show', project_application %></td>
    <td><%= link_to 'Edit', edit_project_application_path(project_application) %></td>
    <td><%= link_to 'Destroy', project_application, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Project application', new_project_application_path %>

app/views/project_applications/new.html.erb
<h1>New project_application</h1>

<%= render 'form' %>

<%= link_to 'Back', project_applications_path %>

app/views/project_applications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Partner:</b>
  <%= @project_application.partner_id %>
</p>

<p>
  <b>Description:</b>
  <%= @project_application.description %>
</p>

<p>
  <b>Number of consultants:</b>
  <%= @project_application.number_of_consultants %>
</p>

<p>
  <b>Accepted:</b>
  <%= @project_application.accepted %>
</p>

<p>
  <b>Open:</b>
  <%= @project_application.open %>
</p>


<%= link_to 'Edit', edit_project_application_path(@project_application) %> |
<%= link_to 'Back', project_applications_path %>