config/routes.rb
TCinGC::Application.routes.draw do
  resources :student_scorecards

  resources :project_scorecards

  resources :project_applications

  resources :student_applications

  resources :partners
  
  resources :assignments

  devise_for :users

  root :to => 'home#index'

  
  root :to => "home#index"
end

app/models/student_application.rb
class StudentApplication < ActiveRecord::Base
	# Setup accessible (or protected) attributes for your model
	attr_accessible :resume, :transcript, :statement_of_interest, :accepted, :open

	# Relationships
	belongs_to :user
	has_many :student_scorecards
end

app/controllers/student_applications_controller.rb
class StudentApplicationsController < ApplicationController
  # GET /student_applications
  # GET /student_applications.json
  def index
    @student_applications = StudentApplication.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @student_applications }
    end
  end

  # GET /student_applications/1
  # GET /student_applications/1.json
  def show
    @student_application = StudentApplication.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @student_application }
    end
  end

  # GET /student_applications/new
  # GET /student_applications/new.json
  def new
    @student_application = StudentApplication.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @student_application }
    end
  end

  # GET /student_applications/1/edit
  def edit
    @student_application = StudentApplication.find(params[:id])
  end

  # POST /student_applications
  # POST /student_applications.json
  def create
    @student_application = StudentApplication.new(params[:student_application])

    respond_to do |format|
      if @student_application.save
        format.html { redirect_to @student_application, notice: 'Student application was successfully created.' }
        format.json { render json: @student_application, status: :created, location: @student_application }
      else
        format.html { render action: "new" }
        format.json { render json: @student_application.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /student_applications/1
  # PUT /student_applications/1.json
  def update
    @student_application = StudentApplication.find(params[:id])

    respond_to do |format|
      if @student_application.update_attributes(params[:student_application])
        format.html { redirect_to @student_application, notice: 'Student application was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @student_application.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /student_applications/1
  # DELETE /student_applications/1.json
  def destroy
    @student_application = StudentApplication.find(params[:id])
    @student_application.destroy

    respond_to do |format|
      format.html { redirect_to student_applications_url }
      format.json { head :ok }
    end
  end
end

app/helpers/student_applications_helper.rb
module StudentApplicationsHelper
end

app/views/student_applications/_form.html.erb
<%= form_for(@student_application) do |f| %>
  <% if @student_application.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student_application.errors.count, "error") %> prohibited this student_application from being saved:</h2>

      <ul>
      <% @student_application.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :resume %><br />
    <%= f.text_field :resume %>
  </div>
  <div class="field">
    <%= f.label :transcript %><br />
    <%= f.text_field :transcript %>
  </div>
  <div class="field">
    <%= f.label :statement_of_interest %><br />
    <%= f.text_field :statement_of_interest %>
  </div>
  <div class="field">
    <%= f.label :accepted %><br />
    <%= f.check_box :accepted %>
  </div>
  <div class="field">
    <%= f.label :open %><br />
    <%= f.check_box :open %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/student_applications/edit.html.erb
<h1>Editing student_application</h1>

<%= render 'form' %>

<%= link_to 'Show', @student_application %> |
<%= link_to 'Back', student_applications_path %>

app/views/student_applications/index.html.erb
<h1>Listing student_applications</h1>

<table>
  <tr>
    <th>User</th>
    <th>Resume</th>
    <th>Transcript</th>
    <th>Statement of interest</th>
    <th>Accepted</th>
    <th>Open</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @student_applications.each do |student_application| %>
  <tr>
    <td><%= student_application.user_id %></td>
    <td><%= student_application.resume %></td>
    <td><%= student_application.transcript %></td>
    <td><%= student_application.statement_of_interest %></td>
    <td><%= student_application.accepted %></td>
    <td><%= student_application.open %></td>
    <td><%= link_to 'Show', student_application %></td>
    <td><%= link_to 'Edit', edit_student_application_path(student_application) %></td>
    <td><%= link_to 'Destroy', student_application, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Student application', new_student_application_path %>

app/views/student_applications/new.html.erb
<h1>New student_application</h1>

<%= render 'form' %>

<%= link_to 'Back', student_applications_path %>

app/views/student_applications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @student_application.user_id %>
</p>

<p>
  <b>Resume:</b>
  <%= @student_application.resume %>
</p>

<p>
  <b>Transcript:</b>
  <%= @student_application.transcript %>
</p>

<p>
  <b>Statement of interest:</b>
  <%= @student_application.statement_of_interest %>
</p>

<p>
  <b>Accepted:</b>
  <%= @student_application.accepted %>
</p>

<p>
  <b>Open:</b>
  <%= @student_application.open %>
</p>


<%= link_to 'Edit', edit_student_application_path(@student_application) %> |
<%= link_to 'Back', student_applications_path %>